#!/bin/bash
set -euo pipefail
[[ "${1:-}" =~ ^tortoise-[0-9]{8}T[0-9]{6}Z\.sql$ ]] || {
    echo 'Expected a backup filename generated by backup.sh' >&2
    exit 2
}
sha256sum --check "/backups/$1.sha256"
export MYSQL_PWD="$MARIADB_ROOT_PASSWORD"
mariadb --user=root < "/backups/$1"
bash /ops/check-db.sh
echo 'Backup imported successfully into the disposable restore-test database.'
